#
#Tue Jul 07 22:20:18 COT 2026
appium\:hub=http\://127.0.0.1\:4723
appium\:takesScreenshot=true
appium\:warnings={}
appium\:desired={platformName\=ANDROID, appPackage\=com.example.foamwash, fullReset\=false, hub\=http\://127.0.0.1\:4723, automationName\=UIAutomator2, appActivity\=.MainActivity, noReset\=true, autoGrantPermissions\=true, udid\=320615888739}
appium\:deviceApiLevel=30
appium\:automationName=UIAutomator2
appium\:fullReset=false
appium\:locationContextEnabled=false
appium\:deviceScreenSize=720x1600
appium\:deviceManufacturer=ZTE
appium\:udid=320615888739
appium\:pixelRatio=2
appium\:autoGrantPermissions=true
platformName=ANDROID
appium\:networkConnectionEnabled=true
appium\:deviceScreenDensity=320
appium\:viewportRect={left\=0, top\=66, width\=720, height\=1534}
appium\:deviceModel=ZTE A7030
appium\:platformVersion=11
appium\:noReset=true
appium\:databaseEnabled=false
appium\:deviceUDID=320615888739
appium\:statBarHeight=66
appium\:webStorageEnabled=false
appium\:appActivity=.MainActivity
appium\:deviceName=320615888739
appium\:javascriptEnabled=true
appium\:appPackage=com.example.foamwash
