server {
    listen 80;

    # Servir archivos estáticos de React/Vite
    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Necesario para React Router: todas las rutas van al index.html
        try_files $uri $uri/ /index.html;
    }
}