[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "node dist/main"
restartPolicyType = "on_failure"

[build.nixpacksPlan.phases.build]
cacheDirectories = []