sonar.projectKey=FoamWash
sonar.host.url=http://localhost:9000
sonar.token=sqp_31eef002db063d922dedce10c9d796ddcd382d56
sonar.sources=src
sonar.tests=src/test
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info