sonar.projectKey=Foam-Wash-Backend
sonar.host.url=http://localhost:9000
sonar.token=sqp_1db46c4ec7fa6c447d21425dd0fd118d1dfdb0fa
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**