version: '3.8'

services:
  backend:
    build: ./backend
    restart: on-failure
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      DATABASE_URL: "mysql://root:rootpassword@mysql:3306/foam_wash_db"
      JWT_SECRET: cambia_esto_por_un_secreto_seguro_min32chars
      JWT_REFRESH_SECRET: otro_secreto_diferente_para_refresh_min32chars
      JWT_EXPIRES_IN: 7d
      PORT: 5000
      NODE_ENV: development
      FRONTEND_URL: http://localhost:3000
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USER: foamwashlg@gmail.com
      EMAIL_PASS: rvsdnpfazhfxudgn
      EMAIL_FROM: "FoamWash <noreply@foamwash.com>"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mysql:
    image: mysql:8
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: foam_wash_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data: